services:
  sms:
    container_name: sms
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
