services:
  sms:
    container_name: sms
    restart: unless-stopped
    build:
      context: ./
      dockerfile: ./Dockerfile.dev
    ports:
      - '${APP_PORT}:${APP_PORT}'
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    networks:
      - sms-network

  mailhog:
    container_name: mailhot
    restart: unless-stopped
    image: mailhog/mailhog
    ports:
      - '1025:1025'
      - '8025:8025'
    networks:
      - sms-network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8025/']
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  sms-network:
    driver: bridge
